spring:
  application:
      name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: ACCOUNT-SERVICE
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=api/account/**
server:
   port: 9193
   error:
    include-message: always
eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} 
  client:
      serviceUrl:
        defaultZone: http://localhost:8762/eureka/ 
management:
  endpoints:
    web:
      exposure:
        include: "*"
jwt:
  secret: mySecretKey
  expireMs: 12000000
  refrEshexpireMs: 12000000
